# Site settings
title: Streamline Identity Management Playbook
name: Streamline Identity Management Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Identity Guidance
baseurl: '/ficam-identity'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-identity/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: program-guides
  description: FICAM Playbook - Streamline Identity Management
  url: https://github.com/gsa/ficam-identity

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Home
  url: index.html
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false
  
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
